### ISSUE TITLE
paper question

### ISSUE THREAD

**Issue by microchila** [vukasin-stanojevic/BoostTrack#10]
![image](https://github.com/user-attachments/assets/1c286975-2daa-4054-88d3-7210608dcf12)

The high-confidence detections in this paragraph in the paper refer to the detection frames that were not matched in the first stage, since the first stage did not match the trajectory, then the second stage of the remaining trajectory and low confidence frames, the high-confidence frames should not have been matched ah!The phrase assign that detection to the wrong object is a bit questionable.

**Comment by vukasin-stanojevic** [comment]
Hello, 
I'm not sure what exact problem you are referring to. I used the terms "assigned" and "matched" interchangeably. 
What I tried to describe is if you have two detection $D_1$ and $D_2$ and two tracklets $T_1$ and $T_2$, the correct match may be (e.g) $T_1-D_2, T_2-D_1$. However, if only $D_1$ has a high confidence score, and similarity between $T_1$ and $D_1$ is slightly greater than similarity between $D_1$ and $T_2$ , $D_1$ will be matched with $T_1$ (even if similarity between $T_1$ and $D_2$ is highest the $T_1-D_2$ pair will not be considered due to low confidence of $D_2$). In the second stage $T_2$ can be only matched with $D_2$, which produces IDSWs.

You may also want to check the cited reference. They also demonstrated (with pictures) the cases where two-stage assignment leads to IDSWs. 

@microchila

**Comment by microchila** [comment]
I understand what you are trying to say, thanks for the answer
